engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "**.js"
exclude_paths:
- test/test.js
- gulpfile.babel.js
- README.md
- circle.yml
- package.json
- test/mocha.opts
- test/sabae.json
