engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.coffee"
exclude_paths:
- test/test.coffee
- gulpfile.js
- README.md
- circle.yml
- package.json
- test/mocha.opts
- test/sabae.json